# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/git_commit_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GitCommitWidget(object):
    def setupUi(self, GitCommitWidget):
        GitCommitWidget.setObjectName("GitCommitWidget")
        GitCommitWidget.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(GitCommitWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(GitCommitWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label = QtWidgets.QLabel(GitCommitWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(GitCommitWidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)

        self.retranslateUi(GitCommitWidget)
        QtCore.QMetaObject.connectSlotsByName(GitCommitWidget)

    def retranslateUi(self, GitCommitWidget):
        _translate = QtCore.QCoreApplication.translate
        GitCommitWidget.setWindowTitle(_translate("GitCommitWidget", "Commit"))
        self.label.setText(_translate("GitCommitWidget", "TextLabel"))
