# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/git_mdi_area_placeholder_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GitMdiAreaPlaceholderWidget(object):
    def setupUi(self, GitMdiAreaPlaceholderWidget):
        GitMdiAreaPlaceholderWidget.setObjectName("GitMdiAreaPlaceholderWidget")
        GitMdiAreaPlaceholderWidget.resize(531, 417)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(GitMdiAreaPlaceholderWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.NoRepositoryOpenedLabel = QtWidgets.QLabel(GitMdiAreaPlaceholderWidget)
        self.NoRepositoryOpenedLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.NoRepositoryOpenedLabel.setWordWrap(True)
        self.NoRepositoryOpenedLabel.setObjectName("NoRepositoryOpenedLabel")
        self.verticalLayout_3.addWidget(self.NoRepositoryOpenedLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.LabelsLayout = QtWidgets.QVBoxLayout()
        self.LabelsLayout.setObjectName("LabelsLayout")
        self.CreateNewRepoPushButton = QtWidgets.QLabel(GitMdiAreaPlaceholderWidget)
        self.CreateNewRepoPushButton.setAlignment(QtCore.Qt.AlignCenter)
        self.CreateNewRepoPushButton.setWordWrap(True)
        self.CreateNewRepoPushButton.setObjectName("CreateNewRepoPushButton")
        self.LabelsLayout.addWidget(self.CreateNewRepoPushButton)
        self.ConnectRemoteRepoPushButton = QtWidgets.QLabel(GitMdiAreaPlaceholderWidget)
        self.ConnectRemoteRepoPushButton.setObjectName("ConnectRemoteRepoPushButton")
        self.LabelsLayout.addWidget(self.ConnectRemoteRepoPushButton)
        self.horizontalLayout.addLayout(self.LabelsLayout)
        self.ButtonsLayout = QtWidgets.QVBoxLayout()
        self.ButtonsLayout.setObjectName("ButtonsLayout")
        self.CreateRepoPushButton = QtWidgets.QPushButton(GitMdiAreaPlaceholderWidget)
        self.CreateRepoPushButton.setObjectName("CreateRepoPushButton")
        self.ButtonsLayout.addWidget(self.CreateRepoPushButton)
        self.ConnectRepoPushButton = QtWidgets.QPushButton(GitMdiAreaPlaceholderWidget)
        self.ConnectRepoPushButton.setObjectName("ConnectRepoPushButton")
        self.ButtonsLayout.addWidget(self.ConnectRepoPushButton)
        self.horizontalLayout.addLayout(self.ButtonsLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)

        self.retranslateUi(GitMdiAreaPlaceholderWidget)
        QtCore.QMetaObject.connectSlotsByName(GitMdiAreaPlaceholderWidget)

    def retranslateUi(self, GitMdiAreaPlaceholderWidget):
        _translate = QtCore.QCoreApplication.translate
        GitMdiAreaPlaceholderWidget.setWindowTitle(_translate("GitMdiAreaPlaceholderWidget", "GitMdiAreaPlaceholderWidget"))
        self.NoRepositoryOpenedLabel.setText(_translate("GitMdiAreaPlaceholderWidget", "No Git repository has been loaded. Use buttons below to create a new repository or use an existing one"))
        self.CreateNewRepoPushButton.setText(_translate("GitMdiAreaPlaceholderWidget", "Create a new repository in project folder"))
        self.ConnectRemoteRepoPushButton.setText(_translate("GitMdiAreaPlaceholderWidget", "Connect existing remote repository"))
        self.CreateRepoPushButton.setText(_translate("GitMdiAreaPlaceholderWidget", "Create"))
        self.ConnectRepoPushButton.setText(_translate("GitMdiAreaPlaceholderWidget", "Connect..."))
