# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/git_branches_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GitBranchesWidget(object):
    def setupUi(self, GitBranchesWidget):
        GitBranchesWidget.setObjectName("GitBranchesWidget")
        GitBranchesWidget.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(GitBranchesWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(GitBranchesWidget)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.verticalLayout.addWidget(self.treeWidget)

        self.retranslateUi(GitBranchesWidget)
        QtCore.QMetaObject.connectSlotsByName(GitBranchesWidget)

    def retranslateUi(self, GitBranchesWidget):
        _translate = QtCore.QCoreApplication.translate
        GitBranchesWidget.setWindowTitle(_translate("GitBranchesWidget", "Branches"))
