# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/git_diff_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GitDiffWidget(object):
    def setupUi(self, GitDiffWidget):
        GitDiffWidget.setObjectName("GitDiffWidget")
        GitDiffWidget.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(GitDiffWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser = QtWidgets.QTextBrowser(GitDiffWidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)

        self.retranslateUi(GitDiffWidget)
        QtCore.QMetaObject.connectSlotsByName(GitDiffWidget)

    def retranslateUi(self, GitDiffWidget):
        _translate = QtCore.QCoreApplication.translate
        GitDiffWidget.setWindowTitle(_translate("GitDiffWidget", "Diff"))
