# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/git_mdi_area_placeholder_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GitMdiAreaPlaceholderWidget(object):
    def setupUi(self, GitMdiAreaPlaceholderWidget):
        GitMdiAreaPlaceholderWidget.setObjectName("GitMdiAreaPlaceholderWidget")
        GitMdiAreaPlaceholderWidget.resize(531, 417)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(GitMdiAreaPlaceholderWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.NoRepositoryOpenedLabel = QtWidgets.QLabel(GitMdiAreaPlaceholderWidget)
        self.NoRepositoryOpenedLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.NoRepositoryOpenedLabel.setWordWrap(True)
        self.NoRepositoryOpenedLabel.setObjectName("NoRepositoryOpenedLabel")
        self.verticalLayout_3.addWidget(self.NoRepositoryOpenedLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.CreateNewRepoPushButton = QtWidgets.QLabel(GitMdiAreaPlaceholderWidget)
        self.CreateNewRepoPushButton.setObjectName("CreateNewRepoPushButton")
        self.verticalLayout.addWidget(self.CreateNewRepoPushButton)
        self.ConnectRemoteRepoPushButton = QtWidgets.QLabel(GitMdiAreaPlaceholderWidget)
        self.ConnectRemoteRepoPushButton.setObjectName("ConnectRemoteRepoPushButton")
        self.verticalLayout.addWidget(self.ConnectRemoteRepoPushButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(GitMdiAreaPlaceholderWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(GitMdiAreaPlaceholderWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)

        self.retranslateUi(GitMdiAreaPlaceholderWidget)
        QtCore.QMetaObject.connectSlotsByName(GitMdiAreaPlaceholderWidget)

    def retranslateUi(self, GitMdiAreaPlaceholderWidget):
        _translate = QtCore.QCoreApplication.translate
        GitMdiAreaPlaceholderWidget.setWindowTitle(_translate("GitMdiAreaPlaceholderWidget", "GitMdiAreaPlaceholderWidget"))
        self.NoRepositoryOpenedLabel.setText(_translate("GitMdiAreaPlaceholderWidget", "No Git repository has been loaded. Use buttons below to create a new repository or use an existing one"))
        self.CreateNewRepoPushButton.setText(_translate("GitMdiAreaPlaceholderWidget", "Create new repository"))
        self.ConnectRemoteRepoPushButton.setText(_translate("GitMdiAreaPlaceholderWidget", "Connect existing remote repository"))
        self.pushButton.setText(_translate("GitMdiAreaPlaceholderWidget", "Create..."))
        self.pushButton_2.setText(_translate("GitMdiAreaPlaceholderWidget", "Connect..."))
