# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/git_page_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GitPageWidget(object):
    def setupUi(self, GitPageWidget):
        GitPageWidget.setObjectName("GitPageWidget")
        GitPageWidget.resize(585, 467)
        self.verticalLayout = QtWidgets.QVBoxLayout(GitPageWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.GitMdiArea = QtWidgets.QMdiArea(GitPageWidget)
        self.GitMdiArea.setObjectName("GitMdiArea")
        self.verticalLayout.addWidget(self.GitMdiArea)

        self.retranslateUi(GitPageWidget)
        QtCore.QMetaObject.connectSlotsByName(GitPageWidget)

    def retranslateUi(self, GitPageWidget):
        _translate = QtCore.QCoreApplication.translate
        GitPageWidget.setWindowTitle(_translate("GitPageWidget", "GitPageWidget"))
