# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/add_citation_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddCitationDialog(object):
    def setupUi(self, AddCitationDialog):
        AddCitationDialog.setObjectName("AddCitationDialog")
        AddCitationDialog.setWindowModality(QtCore.Qt.WindowModal)
        AddCitationDialog.resize(800, 600)
        AddCitationDialog.setMinimumSize(QtCore.QSize(640, 480))
        AddCitationDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddCitationDialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.InfoLabel = QtWidgets.QLabel(AddCitationDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InfoLabel.sizePolicy().hasHeightForWidth())
        self.InfoLabel.setSizePolicy(sizePolicy)
        self.InfoLabel.setObjectName("InfoLabel")
        self.verticalLayout.addWidget(self.InfoLabel)
        self.LinkInputLayout = QtWidgets.QHBoxLayout()
        self.LinkInputLayout.setSpacing(15)
        self.LinkInputLayout.setObjectName("LinkInputLayout")
        self.IdentifierLabel = QtWidgets.QLabel(AddCitationDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IdentifierLabel.sizePolicy().hasHeightForWidth())
        self.IdentifierLabel.setSizePolicy(sizePolicy)
        self.IdentifierLabel.setObjectName("IdentifierLabel")
        self.LinkInputLayout.addWidget(self.IdentifierLabel)
        self.IdentifierLineEdit = QtWidgets.QLineEdit(AddCitationDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IdentifierLineEdit.sizePolicy().hasHeightForWidth())
        self.IdentifierLineEdit.setSizePolicy(sizePolicy)
        self.IdentifierLineEdit.setMinimumSize(QtCore.QSize(350, 0))
        self.IdentifierLineEdit.setObjectName("IdentifierLineEdit")
        self.LinkInputLayout.addWidget(self.IdentifierLineEdit)
        self.verticalLayout.addLayout(self.LinkInputLayout)
        self.InfoTextEdit = QtWidgets.QPlainTextEdit(AddCitationDialog)
        self.InfoTextEdit.setReadOnly(True)
        self.InfoTextEdit.setObjectName("InfoTextEdit")
        self.verticalLayout.addWidget(self.InfoTextEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.CheckIdentifierCheckbox = QtWidgets.QCheckBox(AddCitationDialog)
        self.CheckIdentifierCheckbox.setChecked(True)
        self.CheckIdentifierCheckbox.setObjectName("CheckIdentifierCheckbox")
        self.horizontalLayout_2.addWidget(self.CheckIdentifierCheckbox)
        self.ShowInfoPushButton = QtWidgets.QPushButton(AddCitationDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ShowInfoPushButton.sizePolicy().hasHeightForWidth())
        self.ShowInfoPushButton.setSizePolicy(sizePolicy)
        self.ShowInfoPushButton.setObjectName("ShowInfoPushButton")
        self.horizontalLayout_2.addWidget(self.ShowInfoPushButton)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddCitationDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(AddCitationDialog)
        self.buttonBox.accepted.connect(AddCitationDialog.accept)
        self.buttonBox.rejected.connect(AddCitationDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AddCitationDialog)

    def retranslateUi(self, AddCitationDialog):
        _translate = QtCore.QCoreApplication.translate
        AddCitationDialog.setWindowTitle(_translate("AddCitationDialog", "Add citation - ManuWrite"))
        self.InfoLabel.setText(_translate("AddCitationDialog", "Enter link information:"))
        self.IdentifierLabel.setText(_translate("AddCitationDialog", "Identifier:"))
        self.CheckIdentifierCheckbox.setText(_translate("AddCitationDialog", "Check identifier before inserting"))
        self.ShowInfoPushButton.setText(_translate("AddCitationDialog", "Show cite info"))
