# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/add_crossref_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddCrossRefDialog(object):
    def setupUi(self, AddCrossRefDialog):
        AddCrossRefDialog.setObjectName("AddCrossRefDialog")
        AddCrossRefDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddCrossRefDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.IdentifierLabel = QtWidgets.QLabel(AddCrossRefDialog)
        self.IdentifierLabel.setObjectName("IdentifierLabel")
        self.verticalLayout_3.addWidget(self.IdentifierLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.IdentiferLineEdit = QtWidgets.QLineEdit(AddCrossRefDialog)
        self.IdentiferLineEdit.setObjectName("IdentiferLineEdit")
        self.verticalLayout_4.addWidget(self.IdentiferLineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.StructureTreeWidget = QtWidgets.QTreeWidget(AddCrossRefDialog)
        self.StructureTreeWidget.setColumnCount(2)
        self.StructureTreeWidget.setObjectName("StructureTreeWidget")
        self.StructureTreeWidget.headerItem().setText(0, "1")
        self.StructureTreeWidget.headerItem().setText(1, "2")
        self.verticalLayout.addWidget(self.StructureTreeWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddCrossRefDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AddCrossRefDialog)
        self.buttonBox.accepted.connect(AddCrossRefDialog.accept)
        self.buttonBox.rejected.connect(AddCrossRefDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AddCrossRefDialog)

    def retranslateUi(self, AddCrossRefDialog):
        _translate = QtCore.QCoreApplication.translate
        AddCrossRefDialog.setWindowTitle(_translate("AddCrossRefDialog", "Add cross reference - Manuwrite"))
        self.IdentifierLabel.setText(_translate("AddCrossRefDialog", "Identifier"))
