# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/add_crossref_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddCrossRefDialog(object):
    def setupUi(self, AddCrossRefDialog):
        AddCrossRefDialog.setObjectName("AddCrossRefDialog")
        AddCrossRefDialog.resize(436, 342)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddCrossRefDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.IdentifierLabel = QtWidgets.QLabel(AddCrossRefDialog)
        self.IdentifierLabel.setObjectName("IdentifierLabel")
        self.verticalLayout_3.addWidget(self.IdentifierLabel)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.IdentiferLineEdit = QtWidgets.QLineEdit(AddCrossRefDialog)
        self.IdentiferLineEdit.setObjectName("IdentiferLineEdit")
        self.verticalLayout_4.addWidget(self.IdentiferLineEdit)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.CleverRefGroupBox = QtWidgets.QGroupBox(AddCrossRefDialog)
        self.CleverRefGroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.CleverRefGroupBox.setObjectName("CleverRefGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.CleverRefGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.DefaultCleverRefRadioButton = QtWidgets.QRadioButton(self.CleverRefGroupBox)
        self.DefaultCleverRefRadioButton.setObjectName("DefaultCleverRefRadioButton")
        self.verticalLayout_2.addWidget(self.DefaultCleverRefRadioButton)
        self.LCCleverRefRadioButton = QtWidgets.QRadioButton(self.CleverRefGroupBox)
        self.LCCleverRefRadioButton.setObjectName("LCCleverRefRadioButton")
        self.verticalLayout_2.addWidget(self.LCCleverRefRadioButton)
        self.TCCleverRefRadioButton = QtWidgets.QRadioButton(self.CleverRefGroupBox)
        self.TCCleverRefRadioButton.setObjectName("TCCleverRefRadioButton")
        self.verticalLayout_2.addWidget(self.TCCleverRefRadioButton)
        self.NoCleverRefRadioButton = QtWidgets.QRadioButton(self.CleverRefGroupBox)
        self.NoCleverRefRadioButton.setObjectName("NoCleverRefRadioButton")
        self.verticalLayout_2.addWidget(self.NoCleverRefRadioButton)
        self.verticalLayout.addWidget(self.CleverRefGroupBox)
        self.StructureTreeWidget = QtWidgets.QTreeWidget(AddCrossRefDialog)
        self.StructureTreeWidget.setColumnCount(2)
        self.StructureTreeWidget.setObjectName("StructureTreeWidget")
        self.StructureTreeWidget.headerItem().setText(0, "1")
        self.StructureTreeWidget.headerItem().setText(1, "2")
        self.verticalLayout.addWidget(self.StructureTreeWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddCrossRefDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AddCrossRefDialog)
        self.buttonBox.accepted.connect(AddCrossRefDialog.accept)
        self.buttonBox.rejected.connect(AddCrossRefDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AddCrossRefDialog)

    def retranslateUi(self, AddCrossRefDialog):
        _translate = QtCore.QCoreApplication.translate
        AddCrossRefDialog.setWindowTitle(_translate("AddCrossRefDialog", "Add cross reference - Manuwrite"))
        self.IdentifierLabel.setText(_translate("AddCrossRefDialog", "Identifier"))
        self.CleverRefGroupBox.setTitle(_translate("AddCrossRefDialog", "Clever references"))
        self.DefaultCleverRefRadioButton.setText(_translate("AddCrossRefDialog", "Do nothing"))
        self.LCCleverRefRadioButton.setText(_translate("AddCrossRefDialog", "Add reference name (lower-case)"))
        self.TCCleverRefRadioButton.setText(_translate("AddCrossRefDialog", "Add reference name (title-case)"))
        self.NoCleverRefRadioButton.setText(_translate("AddCrossRefDialog", "Disable"))
