# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/add_heading_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddHeadingDialog(object):
    def setupUi(self, AddHeadingDialog):
        AddHeadingDialog.setObjectName("AddHeadingDialog")
        AddHeadingDialog.resize(395, 325)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddHeadingDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.HeadingLevelLayout = QtWidgets.QHBoxLayout()
        self.HeadingLevelLayout.setObjectName("HeadingLevelLayout")
        self.HeadingLevelLabel = QtWidgets.QLabel(AddHeadingDialog)
        self.HeadingLevelLabel.setObjectName("HeadingLevelLabel")
        self.HeadingLevelLayout.addWidget(self.HeadingLevelLabel)
        self.HeadingLevelCombobox = QtWidgets.QComboBox(AddHeadingDialog)
        self.HeadingLevelCombobox.setObjectName("HeadingLevelCombobox")
        self.HeadingLevelCombobox.addItem("")
        self.HeadingLevelCombobox.addItem("")
        self.HeadingLevelCombobox.addItem("")
        self.HeadingLevelCombobox.addItem("")
        self.HeadingLevelCombobox.addItem("")
        self.HeadingLevelCombobox.addItem("")
        self.HeadingLevelLayout.addWidget(self.HeadingLevelCombobox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.HeadingLevelLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.HeadingLevelLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.AutonumberCheckbox = QtWidgets.QCheckBox(AddHeadingDialog)
        self.AutonumberCheckbox.setObjectName("AutonumberCheckbox")
        self.verticalLayout_2.addWidget(self.AutonumberCheckbox)
        self.AutogenIdentifierRadioButton = QtWidgets.QRadioButton(AddHeadingDialog)
        self.AutogenIdentifierRadioButton.setObjectName("AutogenIdentifierRadioButton")
        self.verticalLayout_2.addWidget(self.AutogenIdentifierRadioButton)
        self.ManualIdentifierRadioButton = QtWidgets.QRadioButton(AddHeadingDialog)
        self.ManualIdentifierRadioButton.setObjectName("ManualIdentifierRadioButton")
        self.verticalLayout_2.addWidget(self.ManualIdentifierRadioButton)
        self.NoIdentifierRadioButton = QtWidgets.QRadioButton(AddHeadingDialog)
        self.NoIdentifierRadioButton.setObjectName("NoIdentifierRadioButton")
        self.verticalLayout_2.addWidget(self.NoIdentifierRadioButton)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.MainInputsLayout = QtWidgets.QHBoxLayout()
        self.MainInputsLayout.setObjectName("MainInputsLayout")
        self.InputsLabelsLayout = QtWidgets.QVBoxLayout()
        self.InputsLabelsLayout.setObjectName("InputsLabelsLayout")
        self.IdentifeirLabel = QtWidgets.QLabel(AddHeadingDialog)
        self.IdentifeirLabel.setObjectName("IdentifeirLabel")
        self.InputsLabelsLayout.addWidget(self.IdentifeirLabel)
        self.TextLabel = QtWidgets.QLabel(AddHeadingDialog)
        self.TextLabel.setObjectName("TextLabel")
        self.InputsLabelsLayout.addWidget(self.TextLabel)
        self.MainInputsLayout.addLayout(self.InputsLabelsLayout)
        self.InputsLineEditsLayout = QtWidgets.QVBoxLayout()
        self.InputsLineEditsLayout.setObjectName("InputsLineEditsLayout")
        self.IdentifierLineEdit = QtWidgets.QLineEdit(AddHeadingDialog)
        self.IdentifierLineEdit.setObjectName("IdentifierLineEdit")
        self.InputsLineEditsLayout.addWidget(self.IdentifierLineEdit)
        self.TextLineEdit = QtWidgets.QLineEdit(AddHeadingDialog)
        self.TextLineEdit.setObjectName("TextLineEdit")
        self.InputsLineEditsLayout.addWidget(self.TextLineEdit)
        self.MainInputsLayout.addLayout(self.InputsLineEditsLayout)
        self.verticalLayout.addLayout(self.MainInputsLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddHeadingDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AddHeadingDialog)
        self.buttonBox.accepted.connect(AddHeadingDialog.accept)
        self.buttonBox.rejected.connect(AddHeadingDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AddHeadingDialog)

    def retranslateUi(self, AddHeadingDialog):
        _translate = QtCore.QCoreApplication.translate
        AddHeadingDialog.setWindowTitle(_translate("AddHeadingDialog", "Add heading - Manuwrite"))
        self.HeadingLevelLabel.setText(_translate("AddHeadingDialog", "Heading level:"))
        self.HeadingLevelCombobox.setItemText(0, _translate("AddHeadingDialog", "1"))
        self.HeadingLevelCombobox.setItemText(1, _translate("AddHeadingDialog", "2"))
        self.HeadingLevelCombobox.setItemText(2, _translate("AddHeadingDialog", "3"))
        self.HeadingLevelCombobox.setItemText(3, _translate("AddHeadingDialog", "4"))
        self.HeadingLevelCombobox.setItemText(4, _translate("AddHeadingDialog", "5"))
        self.HeadingLevelCombobox.setItemText(5, _translate("AddHeadingDialog", "6"))
        self.AutonumberCheckbox.setText(_translate("AddHeadingDialog", "Add section number automatically"))
        self.AutogenIdentifierRadioButton.setText(_translate("AddHeadingDialog", "Add identifier automatically"))
        self.ManualIdentifierRadioButton.setText(_translate("AddHeadingDialog", "Add identifier manually"))
        self.NoIdentifierRadioButton.setText(_translate("AddHeadingDialog", "No identifier"))
        self.IdentifeirLabel.setText(_translate("AddHeadingDialog", "Identifeir"))
        self.TextLabel.setText(_translate("AddHeadingDialog", "Heading text"))
