# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/add_link_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddLinkDialog(object):
    def setupUi(self, AddLinkDialog):
        AddLinkDialog.setObjectName("AddLinkDialog")
        AddLinkDialog.setWindowModality(QtCore.Qt.WindowModal)
        AddLinkDialog.resize(446, 207)
        AddLinkDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddLinkDialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.InfoLabel = QtWidgets.QLabel(AddLinkDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InfoLabel.sizePolicy().hasHeightForWidth())
        self.InfoLabel.setSizePolicy(sizePolicy)
        self.InfoLabel.setObjectName("InfoLabel")
        self.verticalLayout.addWidget(self.InfoLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LabelLayout = QtWidgets.QVBoxLayout()
        self.LabelLayout.setObjectName("LabelLayout")
        self.LinkTextLabel = QtWidgets.QLabel(AddLinkDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LinkTextLabel.sizePolicy().hasHeightForWidth())
        self.LinkTextLabel.setSizePolicy(sizePolicy)
        self.LinkTextLabel.setObjectName("LinkTextLabel")
        self.LabelLayout.addWidget(self.LinkTextLabel)
        self.LinkAddressLabel = QtWidgets.QLabel(AddLinkDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LinkAddressLabel.sizePolicy().hasHeightForWidth())
        self.LinkAddressLabel.setSizePolicy(sizePolicy)
        self.LinkAddressLabel.setObjectName("LinkAddressLabel")
        self.LabelLayout.addWidget(self.LinkAddressLabel)
        self.horizontalLayout.addLayout(self.LabelLayout)
        self.InputLayout = QtWidgets.QVBoxLayout()
        self.InputLayout.setObjectName("InputLayout")
        self.LinkTextLineEdit = QtWidgets.QLineEdit(AddLinkDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LinkTextLineEdit.sizePolicy().hasHeightForWidth())
        self.LinkTextLineEdit.setSizePolicy(sizePolicy)
        self.LinkTextLineEdit.setMinimumSize(QtCore.QSize(350, 0))
        self.LinkTextLineEdit.setObjectName("LinkTextLineEdit")
        self.InputLayout.addWidget(self.LinkTextLineEdit)
        self.LinkAddressLineEdit = QtWidgets.QLineEdit(AddLinkDialog)
        self.LinkAddressLineEdit.setMinimumSize(QtCore.QSize(350, 0))
        self.LinkAddressLineEdit.setObjectName("LinkAddressLineEdit")
        self.InputLayout.addWidget(self.LinkAddressLineEdit)
        self.horizontalLayout.addLayout(self.InputLayout)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddLinkDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AddLinkDialog)
        self.buttonBox.accepted.connect(AddLinkDialog.accept)
        self.buttonBox.rejected.connect(AddLinkDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(AddLinkDialog)

    def retranslateUi(self, AddLinkDialog):
        _translate = QtCore.QCoreApplication.translate
        AddLinkDialog.setWindowTitle(_translate("AddLinkDialog", "Add link - ManuWrite"))
        self.InfoLabel.setText(_translate("AddLinkDialog", "Enter link information:"))
        self.LinkTextLabel.setText(_translate("AddLinkDialog", "Link text:"))
        self.LinkAddressLabel.setText(_translate("AddLinkDialog", "Link address:"))
