# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/save_changes_single_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaveChangesSingleDialog(object):
    def setupUi(self, SaveChangesSingleDialog):
        SaveChangesSingleDialog.setObjectName("SaveChangesSingleDialog")
        SaveChangesSingleDialog.resize(453, 133)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SaveChangesSingleDialog.sizePolicy().hasHeightForWidth())
        SaveChangesSingleDialog.setSizePolicy(sizePolicy)
        SaveChangesSingleDialog.setModal(True)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(SaveChangesSingleDialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.IconLabel = QtWidgets.QLabel(SaveChangesSingleDialog)
        self.IconLabel.setObjectName("IconLabel")
        self.horizontalLayout_2.addWidget(self.IconLabel)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, 10, 10, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MessageLabel = QtWidgets.QLabel(SaveChangesSingleDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MessageLabel.sizePolicy().hasHeightForWidth())
        self.MessageLabel.setSizePolicy(sizePolicy)
        self.MessageLabel.setObjectName("MessageLabel")
        self.verticalLayout.addWidget(self.MessageLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(SaveChangesSingleDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Discard|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(SaveChangesSingleDialog)
        self.buttonBox.accepted.connect(SaveChangesSingleDialog.accept)
        self.buttonBox.rejected.connect(SaveChangesSingleDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SaveChangesSingleDialog)

    def retranslateUi(self, SaveChangesSingleDialog):
        _translate = QtCore.QCoreApplication.translate
        SaveChangesSingleDialog.setWindowTitle(_translate("SaveChangesSingleDialog", "Close document - ManuWrite"))
        self.IconLabel.setText(_translate("SaveChangesSingleDialog", "TextLabel"))
        self.MessageLabel.setText(_translate("SaveChangesSingleDialog", "TextLabel"))
