# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/save_changes_multiple_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaveChangesMultipleDialog(object):
    def setupUi(self, SaveChangesMultipleDialog):
        SaveChangesMultipleDialog.setObjectName("SaveChangesMultipleDialog")
        SaveChangesMultipleDialog.resize(479, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SaveChangesMultipleDialog.sizePolicy().hasHeightForWidth())
        SaveChangesMultipleDialog.setSizePolicy(sizePolicy)
        SaveChangesMultipleDialog.setModal(True)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(SaveChangesMultipleDialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.IconLabel = QtWidgets.QLabel(SaveChangesMultipleDialog)
        self.IconLabel.setObjectName("IconLabel")
        self.horizontalLayout_2.addWidget(self.IconLabel)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(10, 10, 10, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MessageLabel = QtWidgets.QLabel(SaveChangesMultipleDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MessageLabel.sizePolicy().hasHeightForWidth())
        self.MessageLabel.setSizePolicy(sizePolicy)
        self.MessageLabel.setWordWrap(True)
        self.MessageLabel.setObjectName("MessageLabel")
        self.verticalLayout.addWidget(self.MessageLabel)
        self.listWidget = QtWidgets.QListWidget(SaveChangesMultipleDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(SaveChangesMultipleDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Discard|QtWidgets.QDialogButtonBox.SaveAll)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(SaveChangesMultipleDialog)
        self.buttonBox.accepted.connect(SaveChangesMultipleDialog.accept)
        self.buttonBox.rejected.connect(SaveChangesMultipleDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SaveChangesMultipleDialog)

    def retranslateUi(self, SaveChangesMultipleDialog):
        _translate = QtCore.QCoreApplication.translate
        SaveChangesMultipleDialog.setWindowTitle(_translate("SaveChangesMultipleDialog", "Close application - ManuWrite"))
        self.IconLabel.setText(_translate("SaveChangesMultipleDialog", "TextLabel"))
        self.MessageLabel.setText(_translate("SaveChangesMultipleDialog", "Some documents have unsaved changes. Do you want to save them?"))
